### ISSUE TITLE
Define scope of scenarios

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#414]

**Comment by abelsiqueira** [comment]
Thinking about the scenario variants specification, slightly based on the diagram in #415.
The main features that I see are:

- Specify using a file what variants will be applied
- Apply these variants in multiple places in the workflow
- Don't allocate memory (don't copy everything) for each one of them
  - This assumes running one variant at a time, so maybe that is the opposite of what we want?

Suggestion using configuration file:

- Create a scenario-variants.abc configuration file
- Use a hierarchical definition in the file:
  - Variants - a name for them, then a list of
  - Stages - the red bubbles on the diagram, then a list of
  - Changes, defined with a limited set of options

Example in yaml:

```yaml
variant:
  - name: Double cap for ocgt->demand
    pre-graph:
      scale-capacity-flow:
        from: ocgt
        to: demand
        factor: 2
  - name: Variant with double demand
    pre-cluster:
      scale-asset-time-series:
        asset: demand
        factor: 2
```

or in TOML:

```toml
[[variant]]
name = "Double cap for ocgt->demand"
[variant.pre-graph.scale-capacity-flow]
from = "ocgt"
to = "demand"
factor = 2.0

[[variant]]
name = "Variant with double demand"
[variant.pre-cluster.scale-asset-time-series]
asset = "demand"
factor = 2.0
```

Suggestion using julia file:

- Create a scenario-variants.jl file
- Use functions or macros to define variants
- work directly with the structures

Example:

```julia
@variant "Double cap for ocgt->demand" begin
    @create_graph begin
        graph["ocgt", "demand"].capacity *= 2
    end
end

@variant "Double demand" begin
    @cluster begin
        asset_profile["demand"] *= 2
    end
end
```

---

The file-based is probably easier to implement for a small number of options, but harder to extend.
The code-based needs more thought.
